services:
  bikes:
    build:
      dockerfile: ./deploy/Dockerfile.analytics
    env_file:
      - local.env
    volumes:
      - .:/app
    links:
      - "postgres:database"
    networks:
      - analytics

  postgres:
    container_name: postgres
    image: postgres:latest
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DBT_PG_PASSWORD}
    restart: unless-stopped
    env_file:
      - local.env
    networks:
      - analytics
    entrypoint:
      - ./deploy/run_pg_init.sh
    build:
      dockerfile: ./deploy/Dockerfile.postgres

networks:
  analytics:
    name: analytics-network
