FROM python:3.10-bullseye

WORKDIR /app

# Install requirements first to take advantage of caching
COPY requirements.txt .
RUN pip install -r requirements.txt

# Copy the rest of the source code
COPY . .

CMD [ "python", "src/python/run_analytics.py"]