bikes:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: bikes
      password: dev
      port: 5432
      dbname: analytics
      schema: dbt_dev
      threads: 4

    prod:
      type: postgres
      host: "{{ env_var('DBT_PG_HOST__PROD') }}"
      user: "{{ env_var('DBT_PG_USER__PROD') }}"
      password: "{{ env_var('DBT_PG_PASSWORD__PROD') }}"
      port: 5432
      dbname: "{{ env_var('DBT_PG_DB__PROD') }}"
      schema: dbt
      threads: 4
