bikes:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      user: bikes
      password: "{{ env_var('DBT_PG_PASSWORD') }}"
      port: 5432
      dbname: nyc
      schema: dbt
      threads: 4

    prod:
      type: postgres
      host: postgres
      user: postgres
      password: "{{ env_var('DBT_PG_PASSWORD') }}"
      port: 5432
      dbname: nyc
      schema: dbt
      threads: 4
